import React from "react";
import Head from "next/head";
import Navbar from "../componets/Navbar";
import styles from "./feeds.module.css";

const Page = ({ data }) => {
  return (
    <>
      <Head>
        <title>My feeds page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.feeds__app}>
        <h1>My Blogs Page</h1>
        <div className={styles.feeds__app_cards}>
          {data.map((feed) => (
            <div className={styles.feeds__app_card} key={feed.id}>
              <h4>{feed.title}</h4>
              <p>{feed.description}</p>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};
export async function getStaticProps() {
  // const response = await fetch(`http://localhost:8080/feeds`);
  // const data = await response.json();
  let data = [
    { id: 1, title: "My blogs 1", description: "My blogs description 1" },
    { id: 2, title: "My blogs 2", description: "My blogs description 2" },
    { id: 3, title: "My blogs 3", description: "My blogs description 3" },
    { id: 4, title: "My blogs 4", description: "My blogs description 4" },
    { id: 5, title: "My blogs 5", description: "My blogs description 5" },
    { id: 6, title: "My blogs 6", description: "My blogs description 6" },
  ];
  return {
    props: {
      data,
    },
  };
}
export default Page;
