import React from "react";
import Head from "next/head";
import Navbar from "../componets/Navbar";
import styles from "./feeds.module.css";

const Page = ({ data }) => {
  return (
    <>
      <Head>
        <title>My feeds page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.feeds__app}>
        <h1>My Blogs Page</h1>
        <div className={styles.feeds__app_cards}>
          {data.map((feed) => (
            <div className={styles.feeds__app_card} key={feed.id}>
              <h4>{feed.title}</h4>
              <p>{feed.description}</p>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};
export async function getStaticProps() {
  const response = await fetch(`http://localhost:8080/feeds`);
  const data = await response.json();
  return {
    props: {
      data,
    },
  };
}
export default Page;
