import Head from "next/head";

import Navbar from "../componets/Navbar.jsx";
import styles from "../styles/Home.module.css";

function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>My blogs page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className={styles.blog__app}>
        <h1>My Blogs Page</h1>
        <div className={styles.blog__app_cards}>
          {data.map((blog) => (
            <div className={styles.blog__app_card} key={blog.id}>
              <h4>{blog.title}</h4>
              <p>{blog.description}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
export async function getStaticProps() {
  // const response = await fetch(`http://localhost:8080/blogs`);
  // const data = await response.json();
  let data = [
    { id: 1, title: "My feeds 1", description: "My feeds description 1" },
    { id: 2, title: "My feeds 2", description: "My feeds description 2" },
    { id: 3, title: "My feeds 3", description: "My feeds description 3" },
    { id: 4, title: "My feeds 4", description: "My feeds description 4" },
    { id: 5, title: "My feeds 5", description: "My feeds description 5" },
    { id: 6, title: "My feeds 6", description: "My feeds description 6" },
  ];
  return {
    props: {
      data,
    },
  };
}
export default Home;
